# Generated by Django 5.2.4 on 2025-07-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='defalut.jpg', null=True, upload_to='image/'),
        ),
    ]
