# Generated by Django 5.2.4 on 2025-07-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image2',
            field=models.ImageField(default='default.jpg', upload_to='photos/'),
        ),
    ]
