# Generated by Django 5.2.4 on 2025-07-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_profile_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image2',
            field=models.ImageField(default='default.jpg', null=True, upload_to='photos/'),
        ),
    ]
