# Generated by Django 5.2.4 on 2025-07-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_profile_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image2',
        ),
    ]
