# Generated by Django 5.2.4 on 2025-07-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_profile_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image2',
            field=models.ImageField(default='default.jpg', null=True, upload_to='photos/'),
        ),
    ]
