# Generated by Django 5.2 on 2025-08-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_profile_email_alter_book_image_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
