# Generated by Django 5.2 on 2025-08-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='profile_name',
        ),
    ]
